format = """
[┌───┤](bold green)$time$ruby
[├─┤ ](bold green)$directory$git_branch
[└─>](bold green) $git_metrics$git_status$character"""

add_newline = false

[directory]
truncation_length = 3
truncate_to_repo	= false
truncation_symbol = "/"

[git_metrics]
disabled = false

[time]
disabled = false
style = "bold green"
format = '[ $time ]($style) '

[ruby]
format = "[ruby $symbol($version )]($style)"
symbol = "🔻 "